alias: Farm Humidity High
description: Humidity at or above 80%
triggers:
  - entity_id: sensor.greenery_s_farm_farm_humidity
    above: 80
    for:
      minutes: 5
    trigger: numeric_state
actions:
  - data:
      title: ⚠️ Farm Humidity High
      message: >-
        Humidity is at {{ trigger.to_state.state }}% - at or above 80%
        threshold.
    action: notify.mobile_app_farm_phone
mode: single
